import Head from 'next/head'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-10 bg-red-200">
        <h1 className="text-3xl font-black">Hello Jimmy</h1>
        <p>
          This is my <strong className="text-dudeBlue">site</strong>
        </p>
      </main>
    </div>
  )
}
