import Head from 'next/head'
import Image from 'next/image'
import screenshotPacks from '../images/screenshot-packs.png'

export default function Home() {
  return (
    <div className="bg-warmGray-900 text-warmGray-200">
      <Head>
        <title>James Thomas - Developer and Dude</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className="py-10 bg-gradient-to-tl from-blueGray-900 to-violet-900 mb-3">
        <div className="max-w-screen-lg mx-auto px-8">
          <h1 className="text-5xl font-black text-white">James Thomas</h1>
          <p className="italic text-lime-200 text-base">
            Friendly dude, making stuff in Osaka, Japan.
          </p>
          <p className="text-2xl font-bold max-w-prose mt-5">
            Heyo! I do front end development, and other work too.
          </p>
          <p className="text-lg max-w-prose">
            I&lsquo;ve got a long and storied relationship with{' '}
            <code>HTML</code>, <code>CSS</code>, and <code>JavaScript</code>,
            but still I manage to get to know them a little deeper each day.
          </p>
          <p className="text-lg max-w-prose">
            My new buds include <code>React</code>, <code>Gatsby</code>, and{' '}
            <code>Tailwind CSS</code>, and we are all having a party. I love my
            friends.
          </p>
        </div>
      </header>
      <div className="max-w-screen-lg mx-auto px-3 min-h-screen flex flex-col justify-between">
        <main className="p-5 bg-gray-800 rounded shadow border border-warmGray-700">
          <h2 className="text-lg tracking-tight text-white border-b border-warmGray-700 pb-5">
            Web Development Portfolio
          </h2>
          <article className="py-5">
            <h3 className="font-bold text-4xl text-lime-300">ZenPop Packs</h3>
            <p className="text-xl">
              <a href="https://promo.zenpop.jp">promo.zenpop.jp</a>
            </p>
            <div className="my-3 leading-none">
              <Image
                src={screenshotPacks}
                alt="Screenshot"
                className="rounded shadow-lg"
              />
            </div>
            <section className="text-warmGray-200">
              <p className="pb-2">
                This website was built so that customers of{' '}
                <a href="https://zenpop.jp/">
                  ZenPop&apos;s subscription service
                </a>{' '}
                could view information about the goods they receive online. It
                replaced the paper information sheets that used to be included
                in the boxes.
              </p>
              <p>
                With this new website customers around the world have more
                language options when receiving ZenPop goods.
              </p>
            </section>
            <h4 className="mt-5 font-bold text-lg text-lime-300">Features</h4>
            <ul className="list-disc list-inside pl-2 text-lime-100">
              <li>Multi-lingual</li>
              <li>Dark Mode</li>
              <li>95+ Lighthouse Score</li>
              <li>Responsive</li>
              <li>Accessible</li>
            </ul>
            <h4 className="mt-5 font-bold text-lg text-lime-300">Built With</h4>
            <ul className="list-disc list-inside pl-2 text-lime-100">
              <li>Gatsby</li>
              <li>Chakra UI</li>
              <li>Airtable</li>
            </ul>
          </article>
        </main>
        <footer className="py-10">
          <p>This is the footer</p>
        </footer>
      </div>
    </div>
  )
}
